# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tichcop

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3c47638906f4cff8328791c7024bc0e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b519e411ae884241acf64593dd57c4e5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d3c47638906f4cff8328791c7024bc0e }}/uetlearner/tichcop_web:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tichcop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6fdbf615ff834de8986388d25eded91d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d3c47638906f4cff8328791c7024bc0e }}/uetlearner/tichcop_web:${{ github.sha }}'